FROM node:20-alpine AS builder

# Set working directory
WORKDIR /app

ARG PROFILE=prod
ENV PROFILE=${PROFILE}

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build -- --configuration=${PROFILE}

FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist/save-me /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

